import React,{useState}from"react";import{createRoot}from"react-dom/client";import{ArrowLeft,ArrowRight,ArrowUpRight,Check,RotateCcw,ShieldCheck}from"lucide-react";import"./styles.css";
const Q=[
["prozess","Welchen Prozess möchtest du prüfen?",["Kundenanfragen / Leads","Angebote / Aufträge","Bewerbungen / Personal","Dokumente / Freigaben","Kundenservice / Kommunikation","Verwaltung / Backoffice","Anderer Prozess"].map(x=>[x,0])],
["haeufigkeit","Wie häufig läuft dieser Prozess ab?",[["Seltener als 10× pro Monat",0],["10–49× pro Monat",1],["50–199× pro Monat",2],["200–499× pro Monat",3],["500× oder öfter pro Monat",4]]],
["zeit","Wie viel manuelle Arbeitszeit benötigt ein Vorgang ungefähr?",[["Unter 2 Minuten",0],["2–5 Minuten",1],["6–10 Minuten",2],["11–20 Minuten",3],["Über 20 Minuten",4]]],
["personen","Wie viele Personen arbeiten regelmäßig an diesem Prozess?",[["1 Person",0],["2 Personen",1],["3–5 Personen",2],["6–10 Personen",3],["Mehr als 10 Personen",4]]],
["abhaengigkeit","Kann der Prozess problemlos von einer anderen Person übernommen werden?",[["Ja, jederzeit – Prozess und Wissen sind sauber dokumentiert",0],["Ja, aber mit kurzer Einarbeitung / Rückfragen",1],["Nur schwer – viel Wissen steckt bei einzelnen Personen",2],["Nein bzw. kaum – ohne die zuständige Person bleibt der Prozess liegen",3]]],
["manuell","Wie manuell ist der Ablauf heute?",[["Weitgehend automatisiert",0],["Wenige manuelle Schritte",1],["Mehrere manuelle Schritte",2],["Überwiegend manuell",3]]],
["systeme","Zwischen wie vielen Systemen oder Tools werden Informationen übertragen?",[["1 System",0],["2 Systeme",1],["3 Systeme",2],["4 oder mehr Systeme",3]]],
["problem","Was sind aktuell die größten Probleme?",[["Kein wesentliches Problem",0],["Zeitaufwand",1],["Fehler / Doppelerfassung",2],["Verzögerungen / Follow-ups",2],["Fehlende Transparenz / Status",2],["Medienbrüche / Systemwechsel",2]]]
];
const Logo=()=> <a className="logo" href="/"><b>↗</b>online<strong>first.</strong></a>;
const CTA=({children="Kostenlosen Effizienzcheck starten"})=><a className="btn primary" href="/effizienzcheck">{children}<ArrowUpRight size={17}/></a>;
function Home(){return <><header><Logo/><nav><a href="#prozess">Prozess</a><a href="#loesungen">Lösungen</a><a href="#cases">Anwendungsfälle</a><a href="#about">Über uns</a></nav><CTA>Effizienzcheck starten</CTA></header>
<section className="hero dark"><div><p className="eyebrow">DIGITALE PROZESSE · BUSINESS SYSTEMS</p><h1>Weniger manuelle Arbeit.<br/><span>Mehr Zeit für dein Unternehmen.</span></h1><p className="lead">Wir analysieren wiederkehrende Geschäftsprozesse und entwickeln digitale Lösungen, die administrative Arbeit, Medienbrüche und unnötige manuelle Schritte reduzieren.</p><CTA/><small>2–3 Minuten · kostenlos · unverbindlich</small></div><div className="workflow"><p>WORKFLOW / LIVE</p>{["Eingang","Analyse","Automatisierung","Ergebnis"].map((x,i)=><div className="flow" key={x}><b>0{i+1}</b><span>{x}</span><ArrowRight/></div>)}</div></section>
<section><p className="eyebrow">DAS PROBLEM</p><h2>Wie viel Zeit verliert dein Unternehmen durch manuelle Abläufe?</h2><div className="grid3">{["Informationen mehrfach erfassen","E-Mails manuell zuordnen","Dokumente prüfen & übertragen","Termine & Aufgaben nachverfolgen","Statusinformationen weitergeben","Daten zwischen Systemen übertragen"].map(x=><article className="card" key={x}><h3>{x}</h3><p>Wiederkehrende manuelle Schritte binden Zeit und schaffen unnötige Übergaben.</p></article>)}</div><p className="callout">Was bei 10 Vorgängen kaum auffällt, wird bei 50, 100 oder 500 Vorgängen im Monat zum Kostenfaktor.</p></section>
<section className="soft" id="prozess"><p className="eyebrow">UNSER ANSATZ</p><h2>Wir automatisieren nicht einfach alles.</h2><p className="copy">Wir starten beim Prozess, nicht bei der Technologie. Wo entsteht Aufwand? Wie häufig? Wie viel Arbeitszeit? Wo entstehen Fehler oder Verzögerungen? Erst dann entwickeln wir eine passende Lösung.</p></section>
<section id="loesungen"><p className="eyebrow">SO ARBEITEN WIR</p><h2>Vom manuellen Prozess zur digitalen Lösung.</h2><div className="grid4">{[["01","Effizienzcheck"],["02","Process Check"],["03","Lösung & Business Case"],["04","Umsetzung"]].map(x=><article className="card" key={x[0]}><b className="blue">{x[0]}</b><h3>{x[1]}</h3><p>Ein klar abgegrenzter Schritt vom Ist-Prozess zur wirtschaftlich sinnvollen Lösung.</p></article>)}</div><CTA/></section>
<section className="dark" id="cases"><p className="eyebrow">LÖSUNGEN</p><h2>Technologie, die sich deinem Prozess anpasst.</h2><div className="grid3">{["Prozessautomatisierung","Individuelle Business-Systeme","Websites & digitale Plattformen"].map(x=><article className="darkcard" key={x}><h3>{x}</h3><p>Technologie wird dort eingesetzt, wo sie konkret Zeit, Kosten oder Prozessrisiken reduziert.</p></article>)}</div></section>
<section><p className="eyebrow">ANWENDUNGSFÄLLE</p><h2>Typische Prozesse mit Automatisierungspotenzial.</h2><div className="grid3">{[["Personaldienstleistung","Bewerbung → Dokumente → Qualifikation → Kandidatenstatus → Follow-up"],["Hausverwaltung","Schadensmeldung → Zuordnung → Dienstleister → Freigabe → Status"],["Handwerk","Kundenanfrage → Qualifizierung → Termin → Angebot → Auftrag"]].map(x=><article className="card" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
<section className="soft"><p className="eyebrow">WIRTSCHAFTLICHER NUTZEN</p><h2>Automatisierung muss sich rechnen.</h2><div className="example"><b>300 Vorgänge × 8 Minuten = 40 Arbeitsstunden / Monat</b><strong>70 % weniger manuelle Arbeit → 28 Stunden zusätzliche Kapazität</strong><small>Rechenbeispiel, keine allgemeine Einsparzusage.</small></div><CTA>Eigenes Potenzial prüfen</CTA></section>
<section id="about"><p className="eyebrow">WARUM ONLINE FIRST</p><h2>Technologie ist für uns Mittel zum Zweck.</h2><p className="copy">Wir verbinden Prozessanalyse, Softwareentwicklung und Automatisierung. Entscheidend ist das Ergebnis: weniger manuelle Arbeit und ein besserer Prozess.</p></section>
<section className="dark final"><h2>Wo verliert dein Unternehmen heute noch unnötig Zeit?</h2><p>Der erste Schritt ist keine Software und kein Verkaufsgespräch.</p><CTA/></section><footer><Logo/><span>Digitale Lösungen für bessere Prozesse.</span></footer></>}
function CheckPage(){const[step,setStep]=useState(0),[a,setA]=useState(()=>Q.map(()=>[]));if(step===Q.length)return <Result a={a} reset={()=>{setA(Q.map(()=>[]));setStep(0)}} edit={()=>setStep(7)}/>;const q=Q[step],sel=a[step],multi=q[0]==="problem";const toggle=i=>setA(old=>old.map((v,k)=>k!==step?v:!multi?[i]:v.includes(i)? v.filter(x=>x!==i):i===0?[0]:[...v.filter(x=>x!==0),i]));return <div className="check dark"><div className="checktop"><Logo/><a href="/"><ArrowLeft/>Zur Website</a></div><main className="box"><div className="meta"><b>EFFIZIENZCHECK</b><span>Frage {step+1} von 8</span></div><div className="progress"><i style={{width:(step+1)/8*100+"%"}}/></div><h1>{q[1]}</h1>{q[0]==="abhaengigkeit"&&<p className="hint">Damit erfassen wir nicht nur Zeitaufwand, sondern auch Abhängigkeiten bei Urlaub, Krankheit oder Personalwechsel.</p>}{multi&&<p className="hint">Mehrfachauswahl möglich. Diese Frage zählt insgesamt maximal 2 Punkte.</p>}<div className="answers">{q[2].map((o,i)=><button key={o[0]} className={"answer "+(sel.includes(i)?"active":"")} onClick={()=>toggle(i)}><span>{sel.includes(i)&&<Check/>}</span>{o[0]}</button>)}</div><div className="nav"><button className="btn secondary" disabled={!step} onClick={()=>setStep(step-1)}><ArrowLeft/>Zurück</button><button className="btn primary" disabled={!sel.length} onClick={()=>setStep(step+1)}>{step===7?"Ergebnis anzeigen":"Weiter"}<ArrowRight/></button></div></main></div>}
function Result({a,reset,edit}){const ps=Q.map((q,i)=>q[0]==="prozess"?0:Math.min(q[0]==="problem"?2:99,a[i].reduce((s,j)=>s+q[2][j][1],0))),score=ps.reduce((x,y)=>x+y,0),lev=score<=8?"Niedriges":score<=16?"Mittleres":"Hohes",dep=ps[4],drivers=Q.map((q,i)=>({q,p:ps[i],v:a[i].map(j=>q[2][j][0]).join(", ")})).filter(x=>x.p>=2).sort((x,y)=>y.p-x.p).slice(0,4);return <div className="check dark"><div className="checktop"><Logo/><a href="/"><ArrowLeft/>Zur Website</a></div><main className="box result"><p className="eyebrow">DEIN ERGEBNIS</p><h1>{lev} Automatisierungspotenzial.</h1><div className="score"><strong>{score}<small> / 23</small></strong><div className="progress"><i style={{width:score/23*100+"%"}}/></div><p>0–8 niedrig · 9–16 mittel · 17–23 hoch</p></div>{dep>=2&&<div className="risk"><ShieldCheck/><div><b>Personenabhängigkeit / Betriebsrisiko</b><p>Der Prozess hängt stark von einzelnen Personen ab. Bei Urlaub, Krankheit oder Personalwechsel kann dadurch ein operatives Risiko entstehen.</p></div></div>}<h2>Was dein Ergebnis treibt</h2><div className="drivers">{drivers.map(x=><article key={x.q[0]}><b>{x.q[1]}</b><p>{x.v}</p><small>{x.p} Punkte</small></article>)}</div><p className="hint">Erste Orientierung auf Basis deiner Angaben – keine Einsparzusage. Technische Machbarkeit und tatsächlicher Nutzen werden erst im Process Check bewertet.</p><div className="next">{score>8&&<a className="btn primary" href="mailto:kontakt@onlinefirst.eu?subject=Process%20Check">Kostenlosen Process Check anfragen</a>}<button className="btn secondary" onClick={reset}><RotateCcw/>Anderen Prozess prüfen</button><button className="edit" onClick={edit}>Antworten ändern</button></div></main></div>}
function App(){return location.pathname.startsWith("/effizienzcheck")?<CheckPage/>:<Home/>}createRoot(document.getElementById("root")).render(<App/>);